// @osm-surface-smoothness/data — public API.
//
// Data is generated by scripts/extract-from-streetcomplete.ts (run `bun run extract`
// from the repo root). This module re-exports it and adds small lookup helpers.

import { catalogue } from './generated/catalogue.js'
import type { MatrixCell, SmoothnessLevel, SurfaceInfo } from './types.js'

export { catalogue }
export type * from './types.js'

/** Resolve a tag value through the alias map (e.g. "concrete:plates" → "concrete"). */
export function normalizeSurface(value: string): string {
  return catalogue.surfaceAliases[value] ?? value
}

/** Surface metadata for a tag value, following aliases. */
export function getSurfaceInfo(surface: string): SurfaceInfo | undefined {
  return catalogue.surfaces[surface] ?? catalogue.surfaces[normalizeSurface(surface)]
}

export interface SmoothnessOption {
  smoothness: string
  cell: MatrixCell
  level: SmoothnessLevel | undefined
}

/**
 * Smoothness options offered for a surface, in StreetComplete's order (best → worst).
 * Returns an empty array for surfaces without a smoothness matrix.
 */
export function getSmoothnessOptionsForSurface(surface: string): SmoothnessOption[] {
  const cells =
    catalogue.smoothnessMatrix[surface] ?? catalogue.smoothnessMatrix[normalizeSurface(surface)]
  if (!cells) return []
  return Object.entries(cells).map(([smoothness, cell]) => ({
    smoothness,
    cell,
    level: catalogue.smoothnessLevels[smoothness],
  }))
}

/** Whether StreetComplete asks the smoothness quest for this surface. */
export function hasSmoothnessQuest(surface: string): boolean {
  return getSurfaceInfo(surface)?.smoothnessQuest ?? false
}
